galaxy_info:
  role_name: haproxy
  description: HAProxy Setup for AAP2 Cluster installations
  author: Nagoor Shaik
  license: MIT
  min_ansible_version: 2.14
  platforms:
    - name: RedHat
      versions:
        - 8
        - 9
  dependencies: []
