namespace: nshaik
name: aap_collection
version: 1.0.16
readme: README.md
authors:
  - Nagoor Shaik <nagoor.s@gmail.com>
description: Common customized roles to support AAP installation
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - common
  - aap2
dependencies:
  "ansible.posix": ">=1.5.4"
  "awx.awx": ">=23.0.0"
  "community.crypto": ">=2.15.1"
  "community.general": ">=7.3.0"
# The URL of the originating SCM repository
repository: https://github.com/snagoor/aap_common
# The URL to any online docs
documentation: https://github.com/snagoor/aap_common
# The URL to the homepage of the collection/project
homepage: https://github.com/snagoor/aap_common
# The URL to the collection issue tracker
issues: https://github.com/snagoor/aap_common/issue/tracker
build_ignore: []
