---
- name: Install Vault RPM repo
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    owner: root
    group: root
    mode: "0644"

- name: Install required RPMs for HashiCorp Vault
  ansible.builtin.dnf:
    name:
      - vault
      - python3-cryptography
    state: present

- name: Create directories for Vault Server storage and SSL certs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0770"
  loop:
    - "{{ hashicorp_vault_data_dir }}"
    - "{{ hashicorp_vault_ssl_dir }}"

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ hashicorp_vault_ssl_dir }}/vault_ca.key"
    size: 4096
    owner: root
    group: vault
    mode: "0640"

- name: Create Certificate Signing Request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ hashicorp_vault_ssl_dir }}/vault_ca.key"
    common_name: "{{ ansible_fqdn }}"
    organization_name: "{{ org_name | default('Red Hat') }}"
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "DNS:secret.{{ ansible_domain }}"
  register: csr

- name: Create self-signed Certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ hashicorp_vault_ssl_dir }}/vault_ca.pem"
    csr_content: "{{ csr['csr'] }}"
    privatekey_path: "{{ hashicorp_vault_ssl_dir }}/vault_ca.key"
    provider: selfsigned
    owner: root
    group: vault
    mode: "0644"

- name: Create Vault configuration file
  ansible.builtin.copy:
    src: vault_config.hcl
    dest: "{{ hashicorp_vault_home_dir }}/vault.hcl"
    owner: root
    group: root
    mode: "0660"

- name: Create Vault server systemd unit file
  ansible.builtin.copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: "0655"
  notify: Restart and enable vault service

- name: Run systemd daemon reload
  ansible.builtin.systemd:
    name: vault
    daemon_reload: true

- name: Write Vault vars to bashrc
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: /root/.bashrc
  loop:
    - export VAULT_ADDR="https://{{ ansible_fqdn }}:8200"
    - export VAULT_CACERT="{{ hashicorp_vault_ssl_dir }}vault_ca.pem"
    - export VAULT_TOKEN="{{ vault_init_parsed['root_token'] | quote }}"

- name: Check Vault status
  ansible.builtin.command: bash -c "source /root/.bashrc; vault status"
  failed_when: false
  changed_when: false
  register: vault_status

- name: Initialize Vault server and grab the keys
  ansible.builtin.command: bash -c "source /root/.bashrc; vault operator init -format json"
  when: "'Initialized        false' in vault_status['stdout_lines']"
  changed_when: "'Initialized        false' in vault_status['stdout_lines']"
  register: vault_init

- name: Parse output of Vault Initialize command
  ansible.builtin.set_fact:
    vault_init_parsed: "{{ vault_init['stdout'] | from_json }}"
  when:
    - vault_init is defined
    - vault_init['changed']

- name: Write Unseal keys to files
  ansible.builtin.copy:
    dest: "unseal_key_{{ index }}"
    content: "{{ item }}"
    owner: root
    group: root
    mode: "0660"
  loop: "{{ vault_init_parsed['unseal_keys_hex'] | flatten(levels=1) }}"
  loop_control:
    index_var: index
  when:
    - vault_init is defined
    - vault_init['changed']
  delegate_to: localhost
  vars:
    ansible_connection: local

- name: Write root token to file
  ansible.builtin.copy:
    content: "{{ vault_init_parsed['root_token'] }}"
    dest: "root_token_key"
    owner: root
    group: root
    mode: "0660"
  when:
    - vault_init is defined
    - vault_init['changed']
  delegate_to: localhost
  vars:
    ansible_connection: local

- name: Unseal Vault
  ansible.builtin.command: bash -c "source /root/.bashrc; vault operator unseal -address=https://{{ ansible_fqdn }}:8200 {{ item }}"
  when:
    - vault_init is defined
    - vault_init['changed']
  changed_when: vault_init['changed']
  loop: "{{ vault_init_parsed['unseal_keys_hex'] | flatten(levels=1) }}"
  loop_control:
    index_var: index
