---
# tasks file for create_ipa_users
- name: Set local variables
  ansible.builtin.set_fact:
    cert_year: "{{ ansible_date_time['year'] | int + validity_years | default(10) }}"
    cert_month: "{{ ansible_date_time['month'] }}"
    cert_day: "{{ ansible_date_time['day'] }}"
    cert_hour: "{{ ansible_date_time['hour'] }}"
    cert_minute: "{{ ansible_date_time['minute'] }}"
    cert_second: "{{ ansible_date_time['second'] }}"

- name: Calculate future expiry date
  ansible.builtin.set_fact:
    krb_expiry_date: "{{ cert_year }}{{ cert_month }}{{ cert_day }}{{ cert_hour }}{{ cert_minute }}{{ cert_second }}"

- name: Create FreeIPA users
  community.general.ipa_user:
    name: "{{ item['name'] }}"
    state: present
    password: "{{ item['password'] }}"
    krbpasswordexpiration: "{{ krb_expiry_date }}"
    givenname: "{{ item['firstname'] }}"
    sn: "{{ item['lastname'] }}"
    ipa_host: "{{ ldap_hostname | default(ansible_fqdn) }}"
    ipa_user: "{{ ldap_username }}"
    ipa_pass: "{{ ldap_password }}"
  loop: "{{ ldap_users }}"
