---
- name: Restart SSHD service
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: true

- name: Force gather facts
  ansible.builtin.setup:

- name: Generate /etc/hosts entries
  ansible.builtin.template:
    dest: /etc/hosts
    src: "{{ slug }}_hosts.j2"
    mode: "0644"
  loop: "{{ groups['all'] }}"
